### ISSUE TITLE
Failure to make

### ISSUE THREAD

**Issue by mccore** [sebastiencs/ls-icons#2]
As you can see in [make-output.txt](https://github.com/sebastiencs/ls-icons/files/1179894/make-output.txt) there is a failure.

**Comment by mccore** [comment]
The solution was to do the following:
`$ make clean`  
`$ CC=clang CXX=clang++ ./configure --prefix=/opt/coreutils`  
`$ make`

**Comment by sebastiencs** [comment]
Thanks for reporting that @mccore.  
Yes I've updated the readme to make compile the project with clang.
