### ISSUE TITLE
Incorrect Icons

### ISSUE THREAD

**Issue by schaden-freude** [sebastiencs/ls-icons#3]
Hi!

The icons for pdf files, images and databases aren't showing up for me as intended. 

![2017-08-09-200456_1168x128_scrot](https://user-images.githubusercontent.com/17528465/29127240-2ae50bb8-7d3e-11e7-961b-7bd7ae9e53ed.png)

Terminator - v1.91; Ubuntu 17.04

**Comment by schaden-freude** [comment]
Fixed by modifying src/ls-icons.c.

**Comment by innerout** [comment]
Sorry but i have the same issue how did you fix it?

**Comment by innerout** [comment]
ping @sebastiencs

**Comment by innerout** [comment]
For future viewers i managed to solve it by reinstalling icons-in-terminal.I am on Arch Linux.
