### ISSUE TITLE
bug-gnulib - Cannot compile

### ISSUE THREAD

**Issue by lfelipe1501** [sebastiencs/ls-icons#6]
lib/freadseek.c:68:3: error: "Please port gnulib freadseek.c to your platform! Look at the definition of getc, getc_unlocked on your system, then report this to
      bug-gnulib."
 #error "Please port gnulib freadseek.c to your platform! Look at the definition of getc, getc_unlocked on your system, then report this to bug-gnulib."
  ^
1 error generated.

**Comment by RuRo** [comment]
Can confirm, that this is an issue. I am on Manjaro (Arch Linux).

**Comment by lfelipe1501** [comment]
yes! it is an error, I use pure Archlinux, and I get that error compiling with the instructions here or using AUR -_-

**Comment by lfelipe1501** [comment]
> Can confirm, that this is an issue. I am on Manjaro (Arch Linux).

**Comment by nothing-fr** [comment]
Same here on Pop!_OS 18.10...

**Comment by innerout** [comment]
@sebastiencs Could you look at this issue it affects all Arch based distros?

**Comment by sebastiencs** [comment]
It should be fixed. Could you confirm ?

**Comment by innerout** [comment]
Yes it is fixed now thanks.

**Comment by zabbal** [comment]
How was it fixed?

**Comment by innerout** [comment]
I removed the old version from my system and compiled the latest source.

**Comment by duard** [comment]
How you did that (I'm on ubuntu)

**Comment by innerout** [comment]
In Archlinux `gnulib` is not shipped as a system dependency, so you can uninstall it. I just removed it and downloaded the gnulib version that was previously working.

**Comment by lfelipe1501** [comment]
you can use ArchLinux compile code

https://aur.archlinux.org/packages/ls-icons/

of course you must adjust some commands for your distribution and thus the compiled will be generated without problems
